name: PR Merged

on:
  pull_request_target:
    branches:
      - main
    types:
      - closed

jobs:
  if_merged:
    runs-on: ubuntu-latest
    steps:
      - name: yuiju offers a heart when a PR is merged
        if: github.event.pull_request.merged == true
        uses: actions/github-script@v9
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '<img width="200" height="200" alt="yuiju heart" src="https://github.com/user-attachments/assets/f9945215-5008-4731-b37b-5772c899580e" />'
            })